# **Day 1**


**1. Write a program to find pair of elements in a list whose sum is equal to x (input given by the user). Take the list elements from the user. Check for NaN values in the list. If present show a message to the user. (interview question)**

In [22]:
arr=input("Enter the list elements :- ").split(' ')
sm=int(input("Enter a number = "))
for i in range(len(arr)):
    if arr[i].isdigit():
        for j in range(i+1,len(arr)):
            if arr[j].isdigit():
                if eval(f'{arr[i]}+{arr[j]}') == sm:
                    print(arr[i],arr[j])
    if not(arr[i].isdigit()):
        print(f"{arr[i]} is NaN")

Enter the list elements :-  2 5 r 6 g 8 9 3 1 4 7
Enter a number =  12


5 7
r is NaN
g is NaN
8 4
9 3


**2. Find the factorial of the number with recursion and without recursion, making individual function for each of them.**

In [8]:
def factrec(n):
    if n != 0:
        return n*factrec(n-1)
    if n == 0:
        return 1
def factnon(n):
    m=1
    for i in range(1,n):
        m*=i
    return m

**3. Write a program to create a 4-digit OTP using `random` methods.**

In [12]:
import random
def OTP():
    return random.randrange(48,58)

otp=''
for i in range(4):
    otp+=chr(OTP())
print(f'OTP = {otp}')

OTP = 2389


**4. Write a user defined function to swap 2 numbers without using a third variable and return the new numbers**

In [13]:
def swapnum():
    global a,b
    a+=b
    b=a-b
    a=a-b
a=int(input("Enter no. for a = "))
b=int(input("Enter no. for b = "))
print(f"Before Swapping\na = {a}\nb = {b}")
swapnum()
print(f"After Swapping\na = {a}\nb = {b}")

Enter no. for a =  47
Enter no. for b =  83


Before Swapping
a = 47
b = 83
After Swapping
a = 83
b = 47


**5. Create 2 dictionaries. If the user enters birth month in number, it will return birth month in string.** For example:

Input: `8`

Output: `August`

In [14]:
a={1:"January", 2:"February", 3:"March", 4:"April", 5:"May", 6:"June", 7:"July", 8:"August", 9:"September", 10:"October", 11:"November", 12:"December"}
u=int(input("Input: "))
print(f"Output: {a[u]}")

Input:  8


Output: August


**6. Write a program to find the dot product of two vectors using `numpy` methods.**

In [18]:
import numpy as np
x=list(map(int,input("Enter elements for vector x = ").split()))
y=list(map(int,input("Enter elements for vector y = ").split()))
x=np.array(x)
y=np.array(y)
z=np.dot(x,y)
print(f"Dot Product = {z}")

Enter elements for vector x =  2 4 6
Enter elements for vector y =  1 3 5


Dot Product = 44


**7. Write a program to make two arrays of shape (1, 20) and (5, 4) respectively and reshape both of them into (2, 10) array using numpy.**

In [26]:
import numpy as np
p=np.full((1,20),1)
q=np.full((5,4),1)
print(f"Array p (1x20) = \n{p}\n")
print(f"Array q (5x4) = \n{q}\n")
p=p.reshape((2, 10))
q=q.reshape((2, 10))
print(f"Array p (2x10) = \n{p}\n")
print(f"Array q (2x10) = \n{q}\n")

Array p (1x20) = 
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

Array q (5x4) = 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Array p (2x10) = 
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]

Array q (2x10) = 
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]



**8.Find the mean, median, mode, standard deviation, and transpose of an numpy array.**

In [37]:
import numpy as np
c=list(map(int,input("Enter elements for array c = ").split()))
c=np.array([c])
me=np.mean(c)
mo=np.median(c)
sd=np.std(c)
tp=np.transpose(c)
print(f"Array = {c}\nMean = {me}\nMedian = {mo}\nStandard Deviation = {sd}\nTranspose = \n{tp}")

Enter elements for array c =  2 6 3 8 4 9 7


Array = [[2 6 3 8 4 9 7]]
Mean = 5.571428571428571
Median = 6.0
Standard Deviation = 2.4411439272335804
Transpose = 
[[2]
 [6]
 [3]
 [8]
 [4]
 [9]
 [7]]


**9. Find the cross product of two 2D numpy arrays using python.**

In [43]:
import numpy as np
def tdarr():
    a=tuple(map(int,input("Enter 2D array shape = ").split()))
    b=[]
    c=[]
    for i in range(a[1]):
        c=list(map(int,input(f"Enter elements for index {i} = ").split()))
        b.append(c)
    return b
r1=np.array(tdarr())
r2=np.array(tdarr())
r3=np.cross(r1,r2)
print(f"Cross Product = {r3}")

Enter 2D array shape =  2 2
Enter elements for index 0 =  1 3
Enter elements for index 1 =  4 6
Enter 2D array shape =  2 2
Enter elements for index 0 =  5 7
Enter elements for index 1 =  8 9


Cross Product = [ -8 -12]


**10. Write a game to implement rock papers scissors in python, where the user will play against the computer. The code will ask for user input (rock, paper, scissor), and the computer will randomly give an output. Also calculate the points at the end of 5 rounds.**

In [8]:
import random as R

ply=0
ai=0
aim=''
ch=("R","P","S")
it={"RR":0, "RS":1, "RP":-1, "SR":-1, "SS":0, "SP":1, "PR":1, "PS":-1, "PP":0}
wl={-1:"\nAI Wins",0:"\nTie",1:"\nPlayer Wins"}
i=0

def points(str,str1):
    global ply,ai
    a=str+str1
    if it[a] > 0:
        ply+=it[a]
    if it[a] < 0:
        ai+=(it[a]*(-1))
    print(wl[it[a]])
    
print('\nRock     = R\nPaper    = P\nScissors = S')
    
while i < 5:
    print(f"\nRound {i+1}")
    a=input("Enter move :- ")
    if a not in ch:
        print("Enter a Valid Choice")
        i-=1
    else:
        aim=R.choice(ch)
        print(f"AI's move :- {aim}")
        points(a,aim)
        i+=1

print("\nGAME OVER\n\n_FINAL_SCORE_")
print(f"\nPLAYER\tAI\n{ply}\t{ai}")

if ply > ai: print("\nYOU ARE VICTORIOUS")
else: print("\nYOU LOSE")


Rock     = R
Paper    = P
Scissors = S

Round 1


Enter move :-  R


AI's move :- S

Player Wins

Round 2


Enter move :-  P


AI's move :- P

Tie

Round 3


Enter move :-  P


AI's move :- S

AI Wins

Round 4


Enter move :-  S


AI's move :- P

Player Wins

Round 5


Enter move :-  R


AI's move :- R

Tie

GAME OVER

_FINAL_SCORE_

PLAYER	AI
2	1

YOU ARE VICTORIOUS
