In [1]:
import numpy as np

In [2]:
#Converting Python sequences to NumPy Arrays
a0=np.array([1,2,3,4])
a1=np.array([[1,2],[3,4]])
a2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [3]:
a0

array([1, 2, 3, 4])

In [4]:
a1

array([[1, 2],
       [3, 4]])

In [5]:
a2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
a=np.array([127,128,129], dtype=np.int8)

In [7]:
a

array([ 127, -128, -127], dtype=int8)

In [8]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b

In [9]:
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


In [10]:
c_signed32 = a - b.astype(np.int32)

In [11]:
print('signed c:', c_signed32, c_signed32.dtype)

signed c: [-3 -3 -3] int64


In [1]:
help('flask')

Help on package flask:

NAME
    flask

PACKAGE CONTENTS
    __main__
    app
    blueprints
    cli
    config
    ctx
    debughelpers
    globals
    helpers
    json (package)
    logging
    scaffold
    sessions
    signals
    templating
    testing
    typing
    views
    wrappers

FUNCTIONS
    __getattr__(name)
    
    escape(...)
        Replace the characters ``&``, ``<``, ``>``, ``'``, and ``"`` in the string with HTML-safe sequences. Use this if you need to display text that might contain such characters in HTML.
        
        If the object has an ``__html__`` method, it is called and the return value is assumed to already be safe for HTML.
        
        :param s: An object to be converted to a string and escaped.
        :return: A :class:`Markup` string with the escaped text.

DATA
    appcontext_popped = <flask.signals._FakeSignal object>
    appcontext_pushed = <flask.signals._FakeSignal object>
    appcontext_tearing_down = <flask.signals._FakeSignal object>


In [2]:
help('django')

No Python documentation found for 'django'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.
